env:
  global:
    - CC_TEST_REPORTER_ID=f926dbf2ed89c7918e7a47f4f14f7d8386cc102d4cfa0a4e84051c6c976975ea

sudo: false
language: ruby
cache: bundler
rvm:
  - 2.7
  - 2.6
  - 2.5

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile

before_install: gem install bundler
install:
  # Rails 4 is not Ruby 2.7 compatible, so we skip this build
  - |
    [[ "${BUNDLE_GEMFILE}" =~ rails_4 && \
      "${TRAVIS_RUBY_VERSION}" =~ 2.7 ]] && exit || true
  # Regular build
  - bundle install --jobs=3 --retry=3

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
