# frozen_string_literal: true

source 'https://rubygems.org'

# A bundle of opinionated Apache Kafka / Confluent Schema Registry helpers.
gem 'rimless', '~> 2.6'
# Thor is a toolkit for building powerful command-line interfaces.
gem 'thor', '~> 1.5'
